#!/usr/bin/env bash

globs=(
  './src/cli/*.spec.ts'
  './src/conf/*.spec.ts'
  './src/container/*.spec.ts'
  './src/event/*.spec.ts'
  './src/http/router/*.spec.ts'
  './src/http/*.spec.ts'
  './src/session/*.spec.ts'
  './src/support/*.spec.ts'
  './src/testing/*.spec.ts'
  './src/testing/container/*.spec.ts'
  './src/testing/cli/*.spec.ts'
  './src/testing/http/*.spec.ts'
)

files=$(printf " %s" "${globs[@]}")


NODE_OPTIONS="--loader ts-node/esm --experimental-specifier-resolution=node" npx tap $files -- --ts

# # router
# NODE_OPTIONS=\"--loader ts-node/esm --experimental-specifier-resolution=node\" npx tap ./src/http/router/*.spec.ts -- --ts

# # services
# NODE_OPTIONS="--loader ts-node/esm --experimental-specifier-resolution=node" npx tap ./src/services/**/*.spec.ts -- --ts

# # http middlewares
# NODE_OPTIONS="--loader ts-node/esm --experimental-specifier-resolution=node" npx tap ./src/http/middlewares/*.spec.ts -- --ts

# # http apis
# NODE_OPTIONS="--loader ts-node/esm --experimental-specifier-resolution=node" npx tap ./src/http/api/*.spec.ts -- --ts
